#!/usr/bin/env bash
set -ex

python plot_3d_views.py
python run_soma_quantification.py

jupyter nbconvert \
	--to 'html' \
	--ExecutePreprocessor.allow_errors=True \
	--ExecutePreprocessor.timeout=-1 \
	--FilesWriter.build_directory=../results \
	--execute soma_asymmetry.ipynb
